const db = require('knex')(require('../../knexfile')[process.env.NODE_ENV || 'development'])

exports.User = require('./schema/user').connect(db)
exports.Poll = require('./schema/poll').connect(db)
exports.Choice = require('./schema/choice').connect(db)
exports.Tag = require('./schema/tag').connect(db)
exports.Vote = require('./schema/vote').connect(db)
exports.View = require('./schema/view').connect(db)
exports.API = require('./schema/api').connect(db)
exports.Comment = require('./schema/comment').connect(db)
